version: 0.0
os: linux
files:
  - source: /
    destination : /home/ubuntu/nodeapp
hooks:
  ApplicationStop:
    - location: application_stop.sh
      timeout: 300
      runas: ubuntu
  BeforeInstall:
    - location: before_install.sh
      timeout:  300
      runas:  ubuntu
  ApplicationStart:
    - location: application_start.sh
      timeout: 300
      runas:  ubuntu
