version: 0.0
os: linux
files:
  - source: /
    destination : /home/ubuntu/nodeapp
hooks:
  ApplicationStop:
    - location: application_stop.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: before_install.sh
      timeout:  300
      runas:  root
  ApplicationStart:
    - location: application_start.sh
      timeout: 300
      runas:  root
